{% set name = "google-cloud-securitycenter" %}
{% set version = "0.7.1" %}
{% set sha256 = "bb33171a1f0fd020c2679d24cbe99fe5e53daf49d1e11205ef472b0933ed9520" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip >=18.1
  run:
    - python
    - google-api-core-grpc >=1.14.0,<2.0.0dev
    - grpc-google-iam-v1 >=0.12.3,<0.13.0dev
    - enum34

test:
  imports:
    - grpc
    - google.iam
    - google.cloud.securitycenter
    - google.cloud.securitycenter_v1

about:
  home: https://github.com/googleapis/python-securitycenter
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Cloud Security Command Center API client library
  description: "Cloud Security Command Center API is a Google Cloud service that provides access to temporal views of assets and findings within an organization.\nSee the [quick start guide](https://googleapis.dev/python/securitycenter/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/securitycenter/latest/index.html
  dev_url: https://github.com/googleapis/python-securitycenter

extra:
  recipe-maintainers:
    - parthea
